DELETE http://localhost:5050/events/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MywiZXhwIjoxNzMxNjEyNjQwLCJ1c2VyX2VtYWlsIjoiZGFubnljcmFjazEzQGdtYWlsLmNvbSJ9.AhybMyrJbaRx2tzU19OqbHA6lmmQNRZgsTA6wIZUDK0


