POST http://localhost:5050/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MiwiZXhwIjoxNzMxNjE1MTAyLCJ1c2VyX2VtYWlsIjoiZGFucmFjazNAZ21haWwuY29tIn0.L4X2bXK01YBkvU773Wc3ITWxES24ahXPAKaQMBKAW0Q


